version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - npm install -g @angular/cli@12.2.16 webpack-cli --unsafe-perm=true
      - npm install --unsafe-perm=true
      - 'ng build --configuration=$BUILD_CONFIG && ng run hypersense:server:production'
artifacts:
  files:
    - .ebextensions/**/*
    - .e2e/**/*
    - dist/**/*
    - dist/server.js
    - Procfile
    - angular.json
    - tsconfig.json
    - tsconfig.app.json
    - tsconfig.spec.json
    - karma.conf.js
    - tslint.json
    - karma.conf.js

